site_name: BASA
site_url: https://Muanai.github.io/basa/
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight
plugins:
  - search
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
nav:
  - Home: index.md